config/routes.rb
BaconAsia::Application.routes.draw do
  https_options = { protocol: 'https' }

  root to: 'questions#new', via: :get

  resources :questions do
    put :upvote, to: 'questions#upvote', as: 'upvote'
    post :answer, to: 'questions#add_answer'
  end
  resources :answers do
    put :upvote, to: 'answers#upvote', as: 'upvote'
  end

  namespace :users do
    resource :account
  end

  scope https_options do
    match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
    match 'auth/failure', to: redirect('/'), via: [:get, :post]
    match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  end
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Voteable

  field :body, type: String

  belongs_to :user
  belongs_to :question

  validates :body, presence: true,
                   length: { maximum: 140 }
end

app/models/concerns/voteable.rb
module Voteable
  extend ActiveSupport::Concern
  include Mongoid::Persistable

  included do
    field :vote_count,        type: Integer, default: 0
    has_many :votes,
             class_name: 'User::Vote',
             as: :voteable

    scope :newest, ->(limit = 50) { where(:created_at.gte => Date.today).limit(limit) }
    scope :recent, ->(limit = nil) { order_by([:created_at, :desc]).limit(limit) }
    scope :trending, ->(limit = 50) { where(:vote_count.gte => 5).limit(limit) }
    scope :popular, order_by([:vote_count, :desc])
  end
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps
  include Voteable

  field :body, type: String

  belongs_to :user
  has_many :answers

  validates :body, presence: true,
                   length: { maximum: 140 }
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Concerns::OmniAuth
  include Concerns::Voting

  field :email,            type: String
  field :first_name,       type: String
  field :last_name,        type: String
  field :gender,           type: Boolean
  field :name,             type: String
  field :admin,            type: Boolean, default: false
  field :super_admin,      type: Boolean, default: false

  has_many :questions
  has_many :answers

  index({ email: 1 }, { unique: true })
  validates :email, presence:   true,
                    uniqueness: { case_sensitive: false },
                    email:      true

  def self.find_by_email(email)
    regex = /^#{Regexp.quote(email.to_s)}$/i
    where(email: regex).first
  end
end

app/models/user/concerns/omni_auth.rb
class User
  module Concerns
    module OmniAuth
      extend ActiveSupport::Concern

      included do
        field :provider,           type: String
        field :uid,                type: String
        field :oauth_token,        type: String
        field :oauth_expires_at,   type: DateTime
      end

      module ClassMethods
        def from_omniauth(auth)
          where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
          end
        end
      end
    end
  end
end

app/models/user/concerns/voting.rb
class User
  module Concerns
    module Voting
      extend ActiveSupport::Concern

      included do
        has_many :votes, class_name: 'User::Vote'
      end

      def toggle_vote!(voteable)
        return unless voteable.kind_of?(Voteable)

        if vote = fetch_vote(voteable)
          vote.destroy
        else
          votes.create!(voteable: voteable)
        end

        self
      end

      def fetch_vote(voteable)
        votes.where(voteable: voteable).first
      end
    end
  end
end

app/models/user/vote.rb
class User
  class Vote
    include Mongoid::Document
    include Mongoid::Timestamps

    after_create :increase_vote
    after_destroy :decrease_vote

    belongs_to :user
    belongs_to :voteable,
               polymorphic: true

    def increase_vote
      self.voteable.inc(vote_count: 1)
    end

    def decrease_vote
      self.voteable.inc(vote_count: -1)
    end

  end
end

app/controllers/answers_controller.rb
class AnswersController < Controller
  include VotingController

  before_filter :find_answer

  def upvote
    if vote(@answer)
      redirect_back_or question_url(@answer.question)
    else
      redirect_to questions_url
    end
  end

  private

  def find_answer
    if params[:id].present?
      @answer = Answer.find(params[:id])
    elsif params[:answer_id].present?
      @answer = Answer.find(params[:answer_id])
    else
      @answer = Answer.new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AuthenticationController

  protect_from_forgery with: :exception
end

app/controllers/concerns/authentication_controller.rb
module AuthenticationController
  extend ActiveSupport::Concern

  included do
    helper_method :current_user
  end

  def require_login
    if logged_in?
      # TODO update session
    else
      flash[:notice] = 'Please login to continue'
      remember_location
      redirect_to root_url
    end
  end

  def logged_in?
    current_user && session[:user_id]
  end

  private

  def remember_location
    session[:return_path] = params[:return_path] || request.fullpath
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/concerns/voting_controller.rb
module VotingController
  extend ActiveSupport::Concern

  def vote(voteable)
    if current_user
      current_user.toggle_vote!(voteable)
    else
      false
    end
  end
end

app/controllers/controller.rb
class Controller < ApplicationController
  layout :current_layout

  protected

  def current_layout
    'application'
  end

  def redirect_back_or(url = root_url)
    begin
      redirect_to(:back)
    rescue
      redirect_to(url)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < Controller
  include VotingController

  before_filter :find_question

  def index
    @questions = Question.popular
  end

  def new; end

  def create
    @question = Question.create(question_params)
    session[:question_ids] ||= []

    if current_user
      flash[:notice] = "Question asked."
    else
      session[:question_ids] << @question.id.to_s
      flash[:notice] = "Question asked. Sign in?"
    end

    redirect_to question_url(@question)
  end

  def show; end

  def add_answer
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to question_url(@question)
    else
      render :show
    end
  end

  def upvote
    if vote(@question)
      redirect_back_or question_url(@question)
    else
      redirect_to root_url
    end
  end

  private

  def find_question
    if params[:id].present?
      @question = Question.find(params[:id])
    elsif params[:question_id].present?
      @question = Question.find(params[:question_id])
    else
      @question = Question.new
    end
  end

  def question_params
    params.require(:question)
          .permit(:body)
          .merge(user: current_user)
  end

  def answer_params
    params.require(:answer)
          .permit(:body)
          .merge(user: current_user, question: @question)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Controller
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    claim_questions(user)
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  private

  def claim_questions(user)
    Question.any_in(id: session[:question_ids])
            .update_all(user_id: user.id)
  end
end

app/controllers/users/accounts_controller.rb
module Users
  class AccountsController < Controller
    before_filter :require_login

    def show
      @user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_new.html.haml
.ba-property
  = label_tag :body, nil, class: 'name' do
    %p.label
  = text_field_tag 'answer[body]', nil, placeholder: 'Got an answer?'

app/views/answers/_show.html.haml
.answer= answer.body
.vote
  = form_tag answer_upvote_url(answer), method: 'put', class: 'answer-form' do
    = button_tag 'vote', value: 'vote'

app/views/layouts/application.html.haml
!!!
%html.no-js{lang: 'en'}
  %head
    %title baconasia
    = javascript_include_tag "top"
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  %body
    .ba-page-header{ role: 'banner' }
      .row-1
        %ul.nav
          %li= link_to "Browse", questions_path
          - if current_user
            %li= link_to "My Account", users_account_path
            %li= link_to "Sign out", signout_path, id: "sign_out"
          - else
            %li= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in"

    = yield
    = javascript_include_tag "bottom"
    = yield :javascript

app/views/questions/_question.html.haml
.question
  = link_to question.body, question_url(question)
  %span= question.vote_count
.vote
  = form_tag question_upvote_url(question), method: 'put', class: 'question-form' do
    = button_tag 'vote', value: 'vote'

app/views/questions/index.html.haml
.ba-question-index.ba-view
  - @questions.each do |question|
    = render 'question', question: question

app/views/questions/new.html.haml
.ba-question.ba-view
  = form_tag questions_url, method: 'post', class: 'question-form' do
    .ba-property
      = label_tag :body, nil, class: 'name' do
        %p.label
      = text_field_tag 'question[body]', @question.body, placeholder: 'Ask anything...'
  = link_to 'Browse', questions_url

app/views/questions/show.html.haml
.ba-question.ba-view
  = render 'question', question: @question
  = form_tag question_answer_url(@question), method: 'post', class: 'question-form' do
    = render 'answers/new'
  .ba-answers
    - if @question.answers.any?
      - @question.answers.popular.each do |answer|
        = render 'answers/show', answer: answer
    - else
      %span There are no answers yet.

app/views/users/accounts/show.html.haml
.ba-user.ba-view
  .ba-questions My Questions
  - @user.questions.recent(5).each do |question|
    .ba-question= question.body
  .ba-answers My Answers
  - @user.answers.recent(5).each do |answer|
    .ba-answer= answer.body